# aBSREL-MH configuration yaml

DataDirectory: /home/tuk13147/work/aBSREL-MH/data/14_Datasets
SubDirectory: ""
FileEndingFasta: ".fa"
FileEndingNewick: ".nwk"
FileEndingNexus: ".nex"
#DataDirectoryNewick: /home/tuk13147/work/aBSREL-MH/data/Empirical_Enard/Trees/BioNJ/ForHyPhy
DataDirectoryNewick: ""
OutputDirectory: /home/tuk13147/work/aBSREL-MH/analysis/14_Datasets
#OutputDirectory: /home/tuk13147/work/aBSREL-MH/analysis/Empirical_Enard

