# BUSTEDS-MH configuration yaml


DataDirectory: /home/tuk13147/work/aBSREL-MH/data/Empirical_Enard
SubDirectory: ""
FileEndingFasta: ".fa"
FileEndingNewick: ".nwk"
DataDirectoryNewick: /home/tuk13147/work/aBSREL-MH/data/Empirical_Enard/Trees/BioNJ/ForHyPhy
OutputDirectory: /home/tuk13147/work/aBSREL-MH/analysis/Empirical_Enard

