name: aBSREL-MH
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - hyphy=2.5.33
  - snakemake=6.3.0  
  - tn93=1.0.6
  - altair=4.1
  - altair_saver=0.5.0
  - biopython=1.78
  - python=3.8
  - pandas=1.2.4
  - mamba
  - ete3
  - seqmagick
